name: telumerce
description: TelU e-commerce

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^2.3.2
  font_awesome_flutter: ^10.1.0
  shared_preferences: ^2.0.15
  http: ^0.13.4
  image_picker: ^0.8.5+3
  clipboard: ^0.1.3
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png